version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
clone_folder: C:\RedditNet
test: off
build_script:
- cmd: dotnet restore
- cmd: dotnet test "C:\RedditNet\Reddit.Net.Tests\Reddit.Net.Tests.csproj"
- cmd: dotnet pack "C:\RedditNet\Reddit.Net\Reddit.Net.csproj" --configuration Release
artifacts:
- path: Reddit.Net\bin\Release\*.nupkg
  name: RedditNet
deploy:
- provider: NuGet
  api_key:
    secure: +R0+I/09nKCPhUFOqoahxQT0FqFL+mIuYGHZNIdmsiSzqukGTh2FtsusOxFk8si6
  artifact: RedditNet