version: 1.0.{build}
image: Visual Studio 2017 RC
configuration: Release
clone_folder: C:\RedditNet
build_script:
- cmd: msbuild "C:\RedditNet\Reddit.Net.sln" /t:restore /m /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
artifacts:
- path: Reddit.Net\Reddit.Net\bin\Release\*.nupkg
  name: RedditNet
deploy:
- provider: NuGet
  api_key:
    secure: +R0+I/09nKCPhUFOqoahxQT0FqFL+mIuYGHZNIdmsiSzqukGTh2FtsusOxFk8si6
  artifact: RedditNet